import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig, type Plugin } from "vitest/config";

import { lazyFacadeSource } from "./scripts/vitest/react-native-shim";

const dirname = path.dirname(fileURLToPath(import.meta.url));

// drizzle-kit's generated drizzle/migrations.js imports the migration
// .sql files as raw strings (Metro asset semantics on-device). Vite has
// no built-in .sql string loader — serve them as default-export string
// modules so the app-importable migration index (A5) loads unmodified
// in tests.
const sqlAsRawString: Plugin = {
  name: "lemastra-sql-as-raw-string",
  load(id) {
    if (id.endsWith(".sql")) {
      return `export default ${JSON.stringify(fs.readFileSync(id, "utf8"))};`;
    }
    return null;
  },
};

// The generated drizzle/migrations.js is ESM syntax inside a
// CommonJS-context package (the repo's package.json has no "type":
// "module"), and vite-node's interop for that shape is order-fragile
// when mixed with externalized CJS deps (drizzle's migrator pulls
// react). On device Metro bundles it fine — only the test pipeline
// needs help. Intercept the app's relative import of the generated
// index and serve the SAME shape as a virtual ESM module assembled
// from the committed journal + .sql artifacts (auto-follows new
// migrations; nothing is hardcoded).
const DRIZZLE_DIR = path.join(dirname, "drizzle");
const VIRTUAL_DRIZZLE_MIGRATIONS = "\0lemastra:drizzle-migrations";

function drizzleMigrationsSource(): string {
  const journal = JSON.parse(
    fs.readFileSync(path.join(DRIZZLE_DIR, "meta", "_journal.json"), "utf8")
  );
  const entries = journal.entries.map(
    (entry: { idx: number; tag: string }) =>
      `m${String(entry.idx).padStart(4, "0")}: ${JSON.stringify(
        fs.readFileSync(path.join(DRIZZLE_DIR, `${entry.tag}.sql`), "utf8")
      )}`
  );
  return [
    "// Virtual module generated by vitest.config.ts from drizzle/ artifacts.",
    `export default { journal: ${JSON.stringify(journal)}, migrations: { ${entries.join(", ")} } };`,
    "",
  ].join("\n");
}

const drizzleMigrationsIndex: Plugin = {
  name: "lemastra-drizzle-migrations-index",
  resolveId(source) {
    if (/drizzle\/migrations(\.js)?$/.test(source)) {
      return VIRTUAL_DRIZZLE_MIGRATIONS;
    }
    return null;
  },
  load(id) {
    if (id === VIRTUAL_DRIZZLE_MIGRATIONS) {
      return drizzleMigrationsSource();
    }
    return null;
  },
};

// react-native alias facade (see scripts/vitest/react-native-shim.ts).
// Written here at CONFIG time — vite transforms test modules in the main
// process before any worker (and thus before the setupFile) runs, so the
// alias target must exist and stay lazy (no raw require at import time).
const nodeRequire = createRequire(path.join(dirname, "vitest.config.ts"));
const facadeDir = path.join(dirname, "node_modules/.cache/lemastra-vitest-rn");
fs.mkdirSync(facadeDir, { recursive: true });
fs.writeFileSync(
  path.join(facadeDir, "rn-require-facade.cjs"),
  lazyFacadeSource(nodeRequire.resolve("react-native")),
  "utf8"
);

// Vitest + React Native Testing Library runner configuration.
//
// Notes:
// - RNTL v14 (with its `test-renderer` peer) runs tests in a plain Node
//   environment — Test Renderer renders to pure JS objects, no simulator.
// - react-native ships Flow-typed sources that plain Node cannot parse;
//   src/test/setup.ts pre-bundles it (flow-stripped) and seeds
//   require.cache before any test module imports run. The alias below
//   routes graph imports through a lazy facade so collection never touches
//   the raw package. See scripts/vitest/react-native-shim.ts.
// - RNTL v14 publishes no Vitest guide; environment/include follow Vitest
//   4 official config docs.
export default defineConfig({
  plugins: [sqlAsRawString, drizzleMigrationsIndex],
  // Mirrors tsconfig.json "paths": "@/assets/*" → ./assets/* (more specific,
  // listed first) and "@/*" → ./src/*, so component tests import app code
  // with the same alias Metro and tsc resolve.
  resolve: {
    alias: [
      { find: /^@\/assets\/(.*)$/, replacement: path.resolve(dirname, "assets/$1") },
      { find: /^@\/(.*)$/, replacement: path.resolve(dirname, "src/$1") },
      { find: /^react-native$/, replacement: path.join(facadeDir, "rn-require-facade.cjs") },
      // expo-sqlite → node:sqlite-backed test facade (03-01). Unlike the
      // react-native facade this is a committed TypeScript module (no
      // prebundling needed — it only uses node builtins); it implements
      // exactly the drizzle expo-sqlite session call surface. See
      // scripts/vitest/expo-sqlite-facade/README.md.
      { find: /^expo-sqlite$/, replacement: path.join(dirname, "scripts/vitest/expo-sqlite-facade/index.ts") },
      // expo device modules → test facades (03-08, same pattern): the
      // crypto/file-system/sharing package entries pull expo-modules-core
      // and crash under plain Node (__DEV__). Per-file vi.mocks take
      // precedence over these aliases; the facades exist so unmocked
      // graphs (the Phase-1 privacy-screen tests, unmodifiable, now
      // rendering DataControls) load device-free. See
      // scripts/vitest/expo-device-facades/README.md.
      { find: /^expo-crypto$/, replacement: path.join(dirname, "scripts/vitest/expo-device-facades/crypto.ts") },
      { find: /^expo-file-system$/, replacement: path.join(dirname, "scripts/vitest/expo-device-facades/file-system.ts") },
      { find: /^expo-sharing$/, replacement: path.join(dirname, "scripts/vitest/expo-device-facades/sharing.ts") },
    ],
  },
  test: {
    environment: "node",
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    setupFiles: ["./src/test/setup.ts"],
  },
});
