import fsSync from "node:fs";
import { createRequire, Module } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin as RolldownPlugin } from "rolldown";

/**
 * React Native test shim for Vitest (plain-Node environment).
 *
 * Problem: react-native ships Flow-typed sources (`import typeof ...`,
 * `} as T` casts) that Metro strips at bundle time but plain Node cannot
 * parse, and its components eagerly touch native modules that do not exist
 * outside a device/simulator. Jest solves this with @react-native/jest-preset
 * (module mocks + babel); Vitest has no equivalent.
 *
 * Fix (zero new dependencies — everything used is already in the tree):
 * 1. Pre-bundle react-native with rolldown (vite 8's bundler), stripping
 *    Flow via the same Hermes-parser + flow babel plugins that
 *    @react-native/babel-preset uses, with Metro-style platform file
 *    resolution (`.ios.js` → `.native.js` → `.js`, ios platform like the
 *    RN jest preset).
 * 2. Inside the bundle, redirect the exact module paths the official jest
 *    preset mocks (ScrollView, Text, View, NativeComponentRegistry,
 *    UIManager, requireNativeComponent, NativeModules, InitializeCore) to
 *    jest-free equivalents — mirroring
 *    @react-native/jest-preset@0.86.2 jest/setup.js.
 * 3. Seed Node's `require.cache` for react-native's resolved id with the
 *    pre-bundled exports BEFORE any test imports run (setupFiles). Both
 *    the Vitest module graph (through a lazy facade alias) and native CJS
 *    requires (RNTL's) share one module instance — identity matters: RNTL
 *    must see the same components the screens under test render.
 *
 * The bundle is cached on disk keyed by the react-native version plus the
 * shim implementation version.
 */

const SHIM_VERSION = "2";
const RN_PLATFORM = "ios"; // matches the react-native jest preset default

const nodeRequire = createRequire(import.meta.url);
const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const cacheDir = path.join(projectRoot, "node_modules/.cache/lemastra-vitest-rn");

export async function installReactNativeTestShim(): Promise<void> {
  const rnPackageId = nodeRequire.resolve("react-native/package.json");
  const rnRoot = path.dirname(rnPackageId);
  const rnVersion: string = JSON.parse(fsSync.readFileSync(rnPackageId, "utf8")).version;
  const bundlePath = path.join(cacheDir, `react-native-${rnVersion}-shim${SHIM_VERSION}.cjs`);

  const rnId = nodeRequire.resolve("react-native");
  if (nodeRequire.cache[rnId]) {
    // Already loaded (e.g. a second setup pass in the same worker).
    return;
  }

  if (!fsSync.existsSync(bundlePath)) {
    fsSync.mkdirSync(cacheDir, { recursive: true });
    await buildRnBundle(path.join(rnRoot, "index.js"), rnRoot, bundlePath);
  }
  fsSync.writeFileSync(facadePath(), lazyFacadeSource(rnId), "utf8");

  // Globals shaped after @react-native/jest-preset jest/setup.js.
  const g = globalThis as Record<string, unknown>;
  if (typeof g.__turboModuleProxy !== "function") {
    g.__turboModuleProxy = (name: string): unknown => turboModuleMock(name);
  }
  if (g.nativeModuleProxy === undefined || g.nativeModuleProxy === null) {
    g.nativeModuleProxy = {};
  }
  if (typeof g.ErrorUtils === "undefined" || g.ErrorUtils === null) {
    g.ErrorUtils = {
      setGlobalHandler: () => undefined,
      getGlobalHandler: () => undefined,
      reportFatalError: (error: unknown) => {
        throw error;
      },
      reportError: () => undefined,
    };
  }
  // The Fabric renderer reads this bare global at module scope; the jest
  // preset provides a plain empty object.
  if (g.nativeFabricUIManager === undefined || g.nativeFabricUIManager === null) {
    g.nativeFabricUIManager = {};
  }
  if (g.IS_REACT_NATIVE_TEST_ENVIRONMENT === undefined) {
    g.IS_REACT_NATIVE_TEST_ENVIRONMENT = true;
  }
  if (g.window === undefined) {
    g.window = globalThis;
  }

  const mod = new Module(rnId);
  mod.filename = rnId;
  mod.exports = nodeRequire(bundlePath);
  mod.loaded = true;
  nodeRequire.cache[rnId] = mod;
}

/**
 * Facade aliased in for bare `react-native` imports (vitest.config.ts
 * writes the same file at config time). LAZY on purpose: modules importing
 * react-native may be collected BEFORE the setupFile seeds require.cache,
 * so the facade must not touch the raw package at import time — only on
 * first property access, which happens at render time (post-setup).
 */
export function lazyFacadeSource(rnId: string): string {
  return [
    `// Generated by scripts/vitest/react-native-shim.ts — do not edit.`,
    `module.exports = new Proxy({}, {`,
    `  get(_target, prop) {`,
    `    if (prop === "__esModule") return false;`,
    `    if (prop === "then" || prop === "toJSON") return undefined;`,
    `    const rn = require(${JSON.stringify(rnId)});`,
    `    const value = rn[prop];`,
    `    return typeof value === "function" ? value.bind(rn) : value;`,
    `  },`,
    `});`,
    ``,
  ].join("\n");
}

function facadePath(): string {
  return path.join(cacheDir, "rn-require-facade.cjs");
}

// ---------------------------------------------------------------------------
// Module mocks (jest-free ports of @react-native/jest-preset@0.86.2)
// ---------------------------------------------------------------------------

const noop = () => undefined;

/** mockNativeComponent: renders a host element named after the view. */
const MOCK_NATIVE_COMPONENT = `
import * as React from "react";
let nativeTag = 1;
export function mockNativeComponent(viewName) {
  class Component extends React.Component {
    constructor(props) {
      super(props);
      this._nativeTag = nativeTag++;
      this.blur = () => undefined;
      this.focus = () => undefined;
      this.measure = () => undefined;
      this.measureInWindow = () => undefined;
      this.measureLayout = () => undefined;
      this.setNativeProps = () => undefined;
    }
    render() {
      return React.createElement(viewName, this.props, this.props.children);
    }
  }
  Component.displayName = viewName === "RCTView" ? "View" : viewName;
  return Component;
}
export function get(name) {
  return mockNativeComponent(name);
}
export function getWithFallback_DEPRECATED(name) {
  return mockNativeComponent(name);
}
export function setRuntimeConfigProvider() {}
export default { get, getWithFallback_DEPRECATED, setRuntimeConfigProvider };
`;

const MOCK_REQUIRE_NATIVE_COMPONENT = `
import * as React from "react";
export default function requireNativeComponent(viewName) {
  class Component extends React.Component {
    render() {
      return React.createElement(viewName, this.props, this.props.children);
    }
  }
  Component.displayName = viewName;
  return Component;
}
`;

const MOCK_UI_MANAGER = `
const UIManager = {
  AndroidViewPager: { Commands: { setPage: () => undefined, setPageWithoutAnimation: () => undefined } },
  blur: () => undefined,
  createView: () => undefined,
  customBubblingEventTypes: {},
  customDirectEventTypes: {},
  dispatchViewManagerCommand: () => undefined,
  focus: () => undefined,
  getViewManagerConfig: (name) => (name === "AndroidDrawerLayout" ? { Constants: { DrawerPosition: { Left: 10 } } } : undefined),
  hasViewManagerConfig: (name) => name === "AndroidDrawerLayout",
  measure: () => undefined,
  manageChildren: () => undefined,
  setChildren: () => undefined,
  updateView: () => undefined,
  AndroidDrawerLayout: { Constants: { DrawerPosition: { Left: 10 } } },
  AndroidTextInput: { Commands: {} },
  ScrollView: { Constants: {} },
  View: { Constants: {} },
};
export default UIManager;
`;

/** mockComponent: class rendering a host element named after the component. */
const makeMockComponentSource = (hostName: string) => `
import * as React from "react";
export default class ${hostName} extends React.Component {
  constructor(props) {
    super(props);
    this.blur = () => undefined;
    this.focus = () => undefined;
    this.measure = () => undefined;
    this.measureInWindow = () => undefined;
    this.measureLayout = () => undefined;
    this.setNativeProps = () => undefined;
    this.scrollTo = () => undefined;
    this.scrollToEnd = () => undefined;
    this.getScrollResponder = () => this;
    this.getScrollableNode = () => null;
    this.getInnerViewNode = () => null;
    this.getInnerViewRef = () => null;
    this.getNativeScrollRef = () => null;
    this.flashScrollIndicators = () => undefined;
    this.scrollResponderZoomTo = () => undefined;
    this.scrollResponderScrollNativeHandleToKeyboard = () => undefined;
  }
  render() {
    return React.createElement(${JSON.stringify(hostName)}, this.props, this.props.children);
  }
}
${hostName}.displayName = ${JSON.stringify(hostName)};
`;

const MOCK_SCROLL_VIEW = `
import * as React from "react";
export default class ScrollView extends React.Component {
  constructor(props) {
    super(props);
    this.blur = () => undefined;
    this.focus = () => undefined;
    this.measure = () => undefined;
    this.measureInWindow = () => undefined;
    this.measureLayout = () => undefined;
    this.setNativeProps = () => undefined;
    this.scrollTo = () => undefined;
    this.scrollToEnd = () => undefined;
    this.getScrollResponder = () => this;
    this.getScrollableNode = () => null;
    this.getInnerViewNode = () => null;
    this.getInnerViewRef = () => null;
    this.getNativeScrollRef = () => null;
    this.flashScrollIndicators = () => undefined;
    this.scrollResponderZoomTo = () => undefined;
    this.scrollResponderScrollNativeHandleToKeyboard = () => undefined;
  }
  render() {
    return React.createElement(
      "RCTScrollView",
      this.props,
      this.props.refreshControl,
      React.createElement("View", null, this.props.children)
    );
  }
}
ScrollView.displayName = "ScrollView";
`;

const MOCK_VIEW_NATIVE_COMPONENT = `
import * as React from "react";
export const Commands = {
  blur: () => undefined,
  focus: () => undefined,
};
export default class View extends React.Component {
  render() {
    return React.createElement("View", this.props, this.props.children);
  }
}
View.displayName = "View";
`;

const MOCK_NATIVE_MODULES = `
export default {
  AlertManager: { alertWithArgs: () => undefined },
  AsyncLocalStorage: {
    multiGet: (keys, callback) => process.nextTick(() => callback(null, [])),
    multiSet: (entries, callback) => process.nextTick(() => callback(null)),
    multiRemove: (keys, callback) => process.nextTick(() => callback(null)),
    multiMerge: (entries, callback) => process.nextTick(() => callback(null)),
    clear: (callback) => process.nextTick(() => callback(null)),
    getAllKeys: (callback) => process.nextTick(() => callback(null, [])),
  },
  DeviceInfo: {
    getConstants: () => ({
      Dimensions: {
        window: { fontScale: 2, height: 1334, scale: 2, width: 750 },
        screen: { fontScale: 2, height: 1334, scale: 2, width: 750 },
      },
      doLeftAndRightSwapInRTL: true,
      isTesting: true,
    }),
  },
  DevSettings: { addMenuItem: () => undefined, reload: () => undefined },
  ImageLoader: {
    getSize: () => Promise.resolve([320, 240]),
    getSizeWithHeaders: () => Promise.resolve({ height: 222, width: 333 }),
    prefetchImage: () => Promise.resolve(),
    prefetchImageWithMetadata: () => Promise.resolve(),
    queryCache: () => Promise.resolve({}),
  },
  ImageViewManager: {
    getSize: (uri, success) => process.nextTick(() => success(320, 240)),
    prefetchImage: () => Promise.resolve(),
  },
  I18nManager: {
    getConstants: () => ({ isRTL: false, doLeftAndRightSwapInRTL: true, localeIdentifier: "en_US" }),
    allowRTL: () => undefined,
    forceRTL: () => undefined,
    swapLeftAndRightInRTL: () => undefined,
  },
  KeyboardObserver: { addListener: () => undefined, removeListeners: () => undefined },
  Networking: {
    sendRequest: () => undefined,
    abortRequest: () => undefined,
    addListener: () => undefined,
    removeListeners: () => undefined,
  },
  PlatformConstants: {
    getConstants: () => ({
      forceTouchAvailable: false,
      interfaceIdiom: "phone",
      osName: "ios",
      osVersion: "18.0",
      reactNativeVersion: { major: 0, minor: 86, patch: 2, prerelease: null },
    }),
  },
  SourceCode: {
    getConstants: () => ({ scriptURL: "file:///ReactNative/test.bundle" }),
  },
  Timing: {
    createTimer: () => undefined,
    deleteTimer: () => undefined,
  },
  UIManager: {
    getConstants: () => ({}),
    getConstantsForViewManager: () => null,
    getViewManagerConfig: () => undefined,
    hasViewManagerConfig: () => false,
  },
};
`;

/** RN-internal module → jest-free mock source (official preset parity). */
const RN_MODULE_MOCKS: ReadonlyArray<{ readonly suffix: string; readonly source: string }> = [
  { suffix: "Libraries/NativeComponent/NativeComponentRegistry.js", source: MOCK_NATIVE_COMPONENT },
  { suffix: "Libraries/ReactNative/requireNativeComponent.js", source: MOCK_REQUIRE_NATIVE_COMPONENT },
  { suffix: "Libraries/ReactNative/UIManager.js", source: MOCK_UI_MANAGER },
  { suffix: "Libraries/Components/ScrollView/ScrollView.js", source: MOCK_SCROLL_VIEW },
  { suffix: "Libraries/Text/Text.js", source: makeMockComponentSource("Text") },
  { suffix: "Libraries/Components/View/View.js", source: makeMockComponentSource("View") },
  { suffix: "Libraries/Components/View/ViewNativeComponent.js", source: MOCK_VIEW_NATIVE_COMPONENT },
  { suffix: "Libraries/BatchedBridge/NativeModules.js", source: MOCK_NATIVE_MODULES },
  { suffix: "Libraries/Core/InitializeCore.js", source: "export default {};\n" },
];

// ---------------------------------------------------------------------------
// Turbo module mocks for remaining native access points
// ---------------------------------------------------------------------------

/**
 * A no-op native module: every property is a function returning
 * undefined. Crucial for feature flags — RN flag getters do
 * `nativeFlagModule[name]?.() ?? defaultValue`, so undefined results keep
 * every experimental path at its JS default.
 */
function makeNoopNativeModule(): unknown {
  return new Proxy(
    {},
    {
      get(_target, prop) {
        if (typeof prop === "symbol") return undefined;
        if (prop === "then" || prop === "toJSON") return undefined;
        return () => undefined;
      },
    }
  );
}

function turboModuleMock(name: string): unknown {
  switch (name) {
    case "DeviceInfo":
      return {
        getConstants: () => ({
          Dimensions: {
            windowPhysicalPixels: {
              width: 320,
              height: 640,
              scale: 2,
              fontScale: 1,
              densityDpi: 320,
              xdpi: 160,
              ydpi: 160,
            },
            screenPhysicalPixels: {
              width: 320,
              height: 640,
              scale: 2,
              fontScale: 1,
              densityDpi: 320,
              xdpi: 160,
              ydpi: 160,
            },
          },
          doLeftAndRightSwapInRTL: false,
          isTesting: false,
        }),
        addListener: () => ({ remove: () => undefined }),
        removeListeners: () => undefined,
      };
    case "PlatformConstants":
      return {
        getConstants: () => ({
          osName: "ios",
          osVersion: "18.0",
          reactNativeVersion: { major: 0, minor: 86, patch: 2, prerelease: null },
          forceTouchAvailable: false,
          interfaceIdiom: "phone",
        }),
      };
    case "SourceCode":
      return {
        getConstants: () => ({
          scriptURL: "file:///ReactNative/test.bundle",
        }),
      };
    default:
      return makeNoopNativeModule();
  }
}

// ---------------------------------------------------------------------------
// Bundle build
// ---------------------------------------------------------------------------

const RN_SCOPE_RE = /[\\/]node_modules[\\/](@react-native[\\/]|react-native[\\/])/;
const ASSET_RE = /\.(png|jpe?g|gif|webp|ttf|otf|svg|mp3|mp4|wav|cairo)$/;

async function buildRnBundle(entry: string, rnRoot: string, outfile: string): Promise<void> {
  // Imported lazily so vitest.config (which never calls this) stays cheap.
  const { rolldown } = await import("rolldown");
  const babel = (await import("@babel/core")).default;
  const flowStripTypes = (await import("@babel/plugin-transform-flow-strip-types")).default;
  const flowEnums = (await import("babel-plugin-transform-flow-enums")).default;
  const reactJsx = (await import("@babel/plugin-transform-react-jsx")).default;
  const hermesParser = (await import("babel-plugin-syntax-hermes-parser")).default;

  const mockFor = (id: string): string | null => {
    for (const mock of RN_MODULE_MOCKS) {
      if (id === path.join(rnRoot, mock.suffix)) {
        return mock.source;
      }
    }
    return null;
  };

  const rnPlugin: RolldownPlugin = {
    name: "lemastra-rn-flow-strip-and-mocks",
    resolveId(specifier, importer) {
      if (!importer) return null; // entry, handled by rolldown input

      // Jest-preset-parity module mocks (matched on the RESOLVED path).
      const fromMock =
        specifier.startsWith("\0") || specifier.startsWith("rn-mock:")
          ? { id: specifier }
          : null;
      if (fromMock) return fromMock;

      if (specifier.startsWith(".") || path.isAbsolute(specifier)) {
        const resolved = resolveMetroStyle(specifier, path.dirname(importer));
        if (resolved) return { id: resolved };
        return null;
      }
      // react-native self-references resolve inside the package
      if (specifier === "react-native" || specifier.startsWith("react-native/")) {
        const rel =
          specifier === "react-native" ? "index.js" : specifier.slice("react-native/".length);
        const resolved = resolveMetroStyle(rel, rnRoot);
        if (resolved) return { id: resolved };
      }
      // @react-native/* satellite packages also ship Flow sources → bundle
      if (specifier.startsWith("@react-native/")) {
        try {
          const resolved = nodeRequire.resolve(specifier, {
            paths: [path.dirname(importer)],
          });
          if (RN_SCOPE_RE.test(resolved)) return { id: resolved };
        } catch {
          // fall through to default resolution
        }
      }
      return null; // bare deps → external via the `external` option
    },
    load(id) {
      if (id.startsWith("rn-mock:")) {
        return RN_MODULE_MOCKS[Number(id.slice("rn-mock:".length))]?.source ?? null;
      }
      if (ASSET_RE.test(id)) {
        return "export default 0;"; // asset requires become inert in tests
      }
      return null;
    },
    transform(code, id) {
      if (!RN_SCOPE_RE.test(id) || !id.endsWith(".js")) {
        return null;
      }
      const mock = mockFor(id);
      if (mock !== null) return { code: mock, map: undefined };
      const result = babel.transformSync(code, {
        babelrc: false,
        configFile: false,
        compact: false,
        filename: id,
        // Same parse/strip stack as @react-native/babel-preset: Hermes
        // parser (Flow superset incl. unparenthesized `as` casts).
        // flow-enums runs BEFORE flow-strip-types: enums are runtime
        // constructs the enums plugin lowers to a const (flow-strip alone
        // would delete the declaration and leave dangling references).
        // JSX lowering last.
        plugins: [
          [hermesParser, { parseLangTypes: "flow" }],
          flowEnums,
          flowStripTypes,
          reactJsx,
        ],
        sourceMaps: true,
      });
      // Rolldown's TransformResult map type is its own SourceMapInput; the
      // babel plugin returns a standard raw sourcemap object — cast through
      // unknown (runtime shape is accepted).
      return {
        code: result.code ?? code,
        map: (result.map ?? undefined) as unknown as never,
      };
    },
  };

  // Redirect mocked modules BEFORE resolution: rewrite the specifier when
  // the metro-style resolution would land on a mocked path.
  const redirectMocks: RolldownPlugin = {
    name: "lemastra-rn-mock-redirect",
    resolveId(specifier, importer) {
      if (!importer) return null;
      const isRelative = specifier.startsWith(".") || path.isAbsolute(specifier);
      if (!isRelative) {
        if (!(specifier === "react-native" || specifier.startsWith("react-native/"))) {
          return null;
        }
      }
      const fromDir = isRelative
        ? path.dirname(importer)
        : rnRoot;
      const rel = isRelative
        ? specifier
        : specifier === "react-native"
          ? "index.js"
          : specifier.slice("react-native/".length);
      const resolved = resolveMetroStyle(rel, fromDir);
      if (!resolved) return null;
      for (let i = 0; i < RN_MODULE_MOCKS.length; i++) {
        if (resolved === path.join(rnRoot, RN_MODULE_MOCKS[i]!.suffix)) {
          return { id: `rn-mock:${i}` };
        }
      }
      return null; // fall through to the main plugin for real files
    },
  };

  const bundle = await rolldown({
    input: entry,
    plugins: [redirectMocks, rnPlugin],
    treeshake: false,
    external(id) {
      if (id.startsWith(".") || path.isAbsolute(id)) return false;
      if (id.startsWith("rn-mock:")) return false;
      if (id === "react-native" || id.startsWith("react-native/")) return false;
      if (id.startsWith("@react-native/")) return false; // Flow sources → bundled
      return true; // every other package loads natively at test time
    },
  });
  try {
    await bundle.write({
      file: outfile,
      format: "cjs",
      sourcemap: "inline",
      banner: "var __DEV__ = true;", // jest-equivalent default for tests
    });
  } finally {
    await bundle.close();
  }
}

/**
 * Metro-style resolution inside react-native: for extension-less
 * specifiers try `.<platform>.js` → `.native.js` → `.js` (then `.json`,
 * then directory index variants). Explicit extensions resolve as-is.
 */
function resolveMetroStyle(specifier: string, fromDir: string): string | null {
  const base = path.resolve(fromDir, specifier);
  const ext = path.extname(base);
  const hasKnownExt = [".js", ".cjs", ".mjs", ".json"].includes(ext);

  const candidates: string[] = [];
  if (hasKnownExt) {
    candidates.push(base);
  } else {
    const platforms = [RN_PLATFORM, "native", ""];
    for (const platform of platforms) {
      const suffix = platform ? `.${platform}` : "";
      candidates.push(`${base}${suffix}.js`, `${base}${suffix}.json`);
    }
    for (const platform of platforms) {
      const suffix = platform ? `.${platform}` : "";
      candidates.push(path.join(base, `index${suffix}.js`), path.join(base, `index${suffix}.json`));
    }
  }

  for (const candidate of candidates) {
    if (isFile(candidate)) return candidate;
  }
  return null;
}

function isFile(p: string): boolean {
  try {
    return fsSync.statSync(p).isFile();
  } catch {
    return false;
  }
}
